### ISSUE TITLE
DOSBox-X project

### ISSUE THREAD

**Issue by Wengier** [aybe/ProgressHierarchy#1]
Hi @aybe! Have not seen you in the DOSBox-X repository for a while. DOSBox-X has seen significant developments in the recent months, including completely redesigned website (http://dosbox-x.com/), new Wiki system (https://github.com/joncampbell123/dosbox-x/wiki), new Windows installer, and many new and exciting features. And I have been working hard to add even more features to it and also trying to make it easier to use than ever. If possible, could we work on it together to make it even better? Thank you very much!

The DOSBox-X repository: https://github.com/joncampbell123/dosbox-x

**Comment by aybe** [comment]
Hi @Wengier ! Sorry but I barely have any more free time these months, I wish days were longer than 24 hours actually!

**Comment by Wengier** [comment]
@aybe I see. In any case, thanks a lot for the work you had done to DOSBox-X before.

**Comment by aybe** [comment]
Thanks but I barely scratched the surface of it, Jon actually did 99.995% of the work 😂.

**Comment by Wengier** [comment]
@aybe The current script for Windows installer for example is based on the preliminary version you initially wrote; it also includes the scripts for integrating into the Windows Explorer's context menu, which are also based on the scripts you wrote (although with upgrades to make them work better). So you had done a good job for DOSBox-X in the past. If you have time in the future, please feel free to come back at any time and rejoin the team. Thanks for your work again.

**Comment by aybe** [comment]
Yeah but when I see how it is now, I feel I've barely done anything lol !

OK, actually I've spotted a few bugs, I'll post them as soon as possible :)

**Comment by Wengier** [comment]
@aybe You are very humble about your work. And I appreciate that you post any issue(s) you have found.
